# Generated by Django 5.0.1 on 2024-03-16 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacionenviada',
            name='tipo_notificacion',
            field=models.CharField(blank=True, choices=[('last_value1', 'Last Value 1'), ('last_value2', 'Last Value 2'), ('last_value3', 'Last Value 3'), ('last_value4', 'Last Value 4')], max_length=20, null=True),
        ),
    ]
