# Generated by Django 5.0.1 on 2024-02-08 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='cedula',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='direccion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
